export const projects = [
  {
    key: "ff",
    preview_image: "ff.png",
    title: "Software products at Futuro Farming",
    description: "Multiple (mobile and web) apps and the underlying backend infrastructure within the last 4 years of building our own company.",
    type: "key",
  },
  {
    key: "lineage",
    preview_image: "lineage.png",
    title: "Data Lineage at BMW Group",
    description: "Researched and implemented a tool (proof of concept) for BMW Group's data lake team to provide a better understanding of the data that is being used in the BMW Group's business. Published via a paper and blog posts.",
    type: "key",
  },
  {
    key: "gtc",
    preview_image: "gtc.gif",
    title: "Grand Theft Candy (iOS App with AR)",
    description: "Developed an Augmented Reality iOS game as assignment at the University of Munich. Place game field in the real world and collect candy to win - but don't get caught by the police!",
    type: "minor",
  },
  {
    key: "lyza",
    preview_image: "lyza.gif",
    title: "Lyza: Spotify Playlist analyzer",
    description: "Analyze and visualize Spotify playlist information via a React Web App using the public Spotify API.",
    type: "minor",
  },
  {
    key: "route-builder",
    preview_image: "route-builder.gif",
    title: "Route builder using vanilla leaflet",
    description: "Enables you to plan a route for your next session of cross-country running. You can place waypoints on the map which will form your route.",
    type: "minor",
  },
  {
    key: "translations",
    preview_image: "translations.png",
    title: "React Native translation tooling",
    description: "Showcase react native project to demonstrate a workflow to transform an excelsheet of translations to a JSON file and leverage it in the application source code.",
    type: "minor",
  },
  {
    key: "dht",
    preview_image: "dht.png",
    title: "DHT11: Humidity and temperature sensor",
    description: "Raspberry PI with a DHT11 humidity and temperature sensor provided insights in our apartment climate via Google Firestore and Telegram Push Notification API.",
    type: "minor",
  },
]